language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
install:
  - pip install poetry
  - poetry install
script:
  - make lint
  - make test

# ignore tags build
branches:
  except:
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/

after_success:
  - codecov